import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQueryClient, useSuspenseQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { useState } from "react";
import { toast } from "sonner";
import {
    Sparkles,
    Filter,
    DollarSign,
    Boxes,
    CheckCircle,
} from "lucide-react";

import {
    DataTable,
    EmptyState,
    KpiCard,
    PageHeader,
    Panel,
    StatusPill,
    num,
    usd,
} from "@/components/scm/primitives";
import { Button } from "@/components/ui/button";
import { inventoryQuery, recommendationsQuery } from "@/lib/scm/queries";
import { approveReplenishmentRecommendation } from "@/lib/scm/scm.functions";

export const Route = createFileRoute("/_authenticated/recommendations")({
    head: () => ({
        meta: [
            { title: "Recommendations Inbox — SUPPLYCHAINIQ" },
            {
                name: "description",
                content:
                    "Automated supply chain recommendations, replenishment actions, freight mode optimizations, and supplier risk mitigations.",
            },
        ],
    }),
    loader: async ({ context }) => {
        await Promise.all([
            context.queryClient.ensureQueryData(recommendationsQuery),
            context.queryClient.ensureQueryData(inventoryQuery),
        ]);
    },
    component: RecommendationsPage,
});

function RecommendationsPage() {
    const { data: recs } = useSuspenseQuery(recommendationsQuery);
    const { data: inventory } = useSuspenseQuery(inventoryQuery);
    const queryClient = useQueryClient();
    const approveRecommendation = useServerFn(approveReplenishmentRecommendation);
    const approvalMutation = useMutation({
        mutationFn: (input: { recommendationId: string; inventoryPositionId: string }) =>
            approveRecommendation({ data: input }),
        onSuccess: async (result) => {
            await queryClient.invalidateQueries({ queryKey: ["scm"] });
            toast.success(`Recommendation approved; ${result.poNumber} created.`);
        },
        onError: (error: Error) => toast.error(`Recommendation approval failed: ${error.message}`),
    });

    const [filterPriority, setFilterPriority] = useState<string>("ALL");

    const filteredRecs = recs.filter((r) =>
        filterPriority === "ALL" ? true : r.priority === filterPriority,
    );

    const totalFinancialImpact = recs.reduce((a, b) => a + b.impactUsd, 0);

    if (recs.length === 0) {
        return (
            <div className="space-y-6">
                <PageHeader
                    title="Recommendations Inbox & Action Engine"
                    subtitle="Automated optimization recommendations generated by server-side analytics"
                    actions={null}
                />
                <div className="flex flex-col items-center justify-center rounded-lg border border-dashed border-border bg-card py-20 text-center gap-4">
                    <div className="size-12 rounded-full bg-primary/10 flex items-center justify-center text-primary">
                        <Sparkles className="size-6" />
                    </div>
                    <div className="max-w-md space-y-1">
                        <h3 className="font-semibold text-foreground text-base">No Recommendations Yet</h3>
                        <p className="text-xs text-muted-foreground leading-relaxed">
                            No current inventory, shipment, or supplier records meet the recommendation rules.
                        </p>
                    </div>
                </div>
            </div>
        );
    }

    return (
        <>
            <PageHeader
                title="Recommendations Inbox & Action Engine"
                subtitle="Automated optimization recommendations generated by server-side analytics, demand models, and exception monitors"
            />

            <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
                <KpiCard
                    label="Generated Recommendations"
                    value={num(recs.length)}
                    hint="Calculated from current workspace records"
                    tone="warning"
                    icon={Sparkles}
                />
                <KpiCard
                    label="Estimated Impact"
                    value={usd(totalFinancialImpact, { compact: true })}
                    hint="Calculated from current records"
                    tone="primary"
                    icon={DollarSign}
                />
                <KpiCard
                    label="Source Inventory Positions"
                    value={num(inventory.rows.length)}
                    hint="Read from current workspace"
                    tone="success"
                    icon={CheckCircle}
                />
                <KpiCard
                    label="Monitored SKUs"
                    value={num(inventory.rows.length)}
                    hint="Continuous background audit"
                    tone="default"
                    icon={Boxes}
                />
            </div>

            <Panel
                title="Recommendations"
                description="Calculated from the current workspace's inventory, shipment, supplier, product, site, and alert records."
                actions={
                    <div className="flex items-center gap-2">
                        <Filter className="size-3.5 text-muted-foreground" />
                        <select
                            value={filterPriority}
                            onChange={(e) => setFilterPriority(e.target.value)}
                            className="rounded-md border border-input bg-background px-2.5 py-1 text-xs text-foreground focus:outline-hidden"
                        >
                            <option value="ALL">All Priorities</option>
                            <option value="CRITICAL">Critical Only</option>
                            <option value="HIGH">High Only</option>
                            <option value="MEDIUM">Medium Only</option>
                        </select>
                    </div>
                }
                className="mt-4"
            >
                {filteredRecs.length === 0 ? (
                    <EmptyState title="No recommendations generated from current records." description="No matching rows were returned by the current recommendation rules." />
                ) : (
                    <DataTable headers={["Recommendation", "Category", "Priority", "Target", "Estimated Impact", "Action"]}>
                        {filteredRecs.map((r) => (
                            <tr key={r.id} className="border-t border-border/60 hover:bg-muted/40 transition-colors">
                                <td className="px-3.5 py-3">
                                    <p className="font-bold text-foreground text-xs">{r.title}</p>
                                    <p className="mt-0.5 text-[11px] text-muted-foreground max-w-md">{r.detail}</p>
                                </td>
                                <td className="px-3.5 py-3 text-xs uppercase text-muted-foreground font-semibold">{r.category}</td>
                                <td className="px-3.5 py-3">
                                    <StatusPill value={r.priority} />
                                </td>
                                <td className="num px-3.5 py-3 text-xs font-semibold text-foreground">{r.sku}</td>
                                <td className="num px-3.5 py-3 font-bold text-primary">{usd(r.impactUsd)}</td>
                                <td className="px-3.5 py-3">
                                    {r.category === "REPLENISHMENT" && r.inventoryPositionId ? (
                                        <Button
                                            size="sm"
                                            className="h-7 gap-1.5 text-[11px] font-bold"
                                            disabled={approvalMutation.isPending}
                                            onClick={() => approvalMutation.mutate({
                                                recommendationId: r.id,
                                                inventoryPositionId: r.inventoryPositionId!,
                                            })}
                                        >
                                            <CheckCircle className="size-3" />
                                            Approve & Create PO
                                        </Button>
                                    ) : (
                                        <span className="text-xs text-muted-foreground">No automated action</span>
                                    )}
                                </td>
                            </tr>
                        ))}
                    </DataTable>
                )}
            </Panel>
        </>
    );
}
